### ISSUE TITLE
Add some screenshots to the readme

### ISSUE THREAD

**Issue by razzeee** [AdamsLair/winforms#3]
Hey there,

I think it would really help, to include some screenshots in the readme :)

Cheers

**Comment by ilexp** [comment]
Hey there,

thanks for tuning in! This repository currently acts purely as a supporting library for [AdamsLair/duality](https://github.com/AdamsLair/duality) and thus it is not very well-documented or polished for third-party use. I might get around to this eventually, but it's not very high on my ToDo for that reason.

As you probably already found out (but mentioning for others who might come across), compiling and running the TestApp project will provide you with an interactive sample of the controls defined in this library.
