### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by Wiering** [AdamsLair/winforms#8]
Hi, I think I had this working in the past (using VS2013), now trying it again in VS2017 I get the following errors (I put the repository into D:\code\AdamsLair.WinForms), it somehow adds an extra space in the path when I try to compile:

Warning		Could not find a part of the path 'D:\code\AdamsLair.WinForms\ \packages\AdamsLair.WinForms.PopupControl.1.0.0.0'.	AdamsLair.WinForms	EXEC		

Warning		The command ""D:\code\AdamsLair.WinForms\.nuget\nuget.exe" install "D:\code\AdamsLair.WinForms\WinForms\packages.config" -source ""   -solutionDir "D:\code\AdamsLair.WinForms\ "" exited with code -1.	AdamsLair.WinForms			

Warning		Could not find a part of the path 'D:\code\AdamsLair.WinForms\ \packages\AdamsLair.WinForms.PopupControl.1.0.0.0'.	AdamsLair.WinForms			

Warning	IDE0006	Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.	AdamsLair.WinForms		1	Active

Error	CS0006	Metadata file 'D:\code\AdamsLair.WinForms\WinForms\bin\Debug\AdamsLair.WinForms.dll' could not be found	TestApp	D:\code\AdamsLair.WinForms\TestApp\CSC	1	Active

**Comment by ilexp** [comment]
Looks like a package restore issue - have you tried to manually restore packages in Visual Studio?

**Comment by Wiering** [comment]
Thanks for responding. I was eventually able to get it working by changing line 51 in NuGet.targets (replacing the extra space by a dot):

` <RestoreCommand>$(NuGetCommand) install "$(PackagesConfig)" -source "$(PackageSources)" $(RequireConsentSwitch) -solutionDir "$(SolutionDir) "</RestoreCommand>`

` <RestoreCommand>$(NuGetCommand) install "$(PackagesConfig)" -source "$(PackageSources)" $(RequireConsentSwitch) -solutionDir "$(SolutionDir)."</RestoreCommand>`
